r2_behavior_server:
  ros__parameters:
    use_sim_time: false
    target_tree: R2_DryRun_WithMocks
    tick_frequency: 5.0

r2_behavior_client:
  ros__parameters:
    use_sim_time: false
    auto_start: false
    start_value: 1
